[package]
name = "prose-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "prose_parser"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
